bmw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mycar.urls", namespace="mycar")),
]

mycar/urls.py
from django.urls import path
from mycar import views

app_name = "mycar"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("date_input", views.date_input, name="date_input"),
    path("capacity", views.capacity, name="capacity"),
    path("bj_capacity", views.bj_capacity, name="bj_capacity"),
    path("qcl_capacity", views.qcl_capacity, name="qcl_capacity"),
    path("pt_pg_capacity", views.pt_pg_capacity, name="pt_pg_capacity"),
    path("car_message", views.car_message, name="car_message"),
    path("qcl_daka", views.qcl_daka, name="qcl_daka"),
    path("pt_daka", views.pt_daka, name="pt_daka"),
    path("pg_daka", views.pg_daka, name="pg_daka"),
    path("date_report", views.date_report, name="date_report"),
]

mycar/models.py
from django.db import models

# Create your models here.

mycar/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")


def date_input(request):
    return render(request, "date_input.html")


def capacity(request):
    return render(request, "capacity.html")


def login(request):
    return render(request, "login.html")


def bj_capacity(request):
    return render(request, "bj_capacity.html")


def qcl_capacity(request):
    return render(request, "qcl_capacity.html")

def pt_pg_capacity(request):
    return render(request, "pt_pg_capacity.html")

def car_message(request):
    return render(request, "car_message.html")

def qcl_daka(request):
    return render(request, "qcl_daka.html")

def pt_daka(request):
    return render(request, "pt_daka.html")

def pg_daka(request):
    return render(request, "pg_daka.html")

def date_report(request):
    return render(request, "date_report.html")

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>济南宝悦行汽车销售服务有限公司</title>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{#    <script src="{% static 'js/bootstrap.js' %}"></script>#}
    <link rel="icon" type="text/css" href="{% static 'images/logo.ico' %}">
</head>
<body>
    <!-- 导航区域开始 -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!--导航头部标题-->
            <div class="navbar-header">
				<a class="navbar-brand">钣喷车间管理系统</a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>

                   <!-- 导航栏登陆信息区域 -->
               
                <div class="nav-login">
                    <span class="label label-info">欢迎：<a href="#">孙博</a></span>
                    <span class="label label-info"><a href="{% url 'mycar:login' %}">退出</a></span>
                </div>
            </div>

            <!-- 导航栏内容区域 -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="{% block nav_home_active %}{% endblock %}">
                        <a href="/">首页 <span class="sr-only">(current)</span></a>
                    </li>
					<li class="{% block nav_data_input_active %}{% endblock %}">
                        <a href="{% url 'mycar:date_input' %}">登记入场</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"
						   role="button" aria-haspopup="true" aria-expanded="false">
							产能状态
							<span class="caret"></span>
						</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'mycar:capacity' %}">车间总产能</a></li>
								<li role="separator" class="divider"></li>
                                <li><a href="{% url 'mycar:bj_capacity' %}">钣金工序产能</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="{% url 'mycar:qcl_capacity' %}">前处理工序产能</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="{% url 'mycar:pt_pg_capacity' %}">喷涂/抛光工序产能</a></li>
							</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"
						   role="button" aria-haspopup="true" aria-expanded="false">
							数据报表
							<span class="caret"></span>
						</a>
							<ul class="dropdown-menu">
								<li><a href="#">钣金工序数据统计报表</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">前处理工序数据统计报表</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">喷涂工序数据统计报表</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="{% url 'mycar:date_report' %}">钣喷车间数据报表</a></li>
							</ul>
					</li>
				</ul>

                <!-- 导航栏搜索栏 -->
                <form class="navbar-form navbar-left hidden-xs">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="WIP/车牌号码">
                    </div>
                    <button type="submit" class="btn btn-default">查询</button>
                </form>

                <!-- 导航栏logo -->
                 <img class="navbar-header-logo hidden-xs" alt="Brand" src="{% static 'images/logo.ico' %}">
			</div>
        </div>
    </nav>
    <!-- 导航内容区域结束 -->

{#主题内容区域#}
{% block main %}{% endblock %}

{#网页底部内容区域#}

    <div class="panel-footer hidden-xs">
        <span>Copyright © 2020 SunBo. All rights reserved.</span>
        <span>|</span>
        <a href="mailto: 309593135@qq.com">E-mail: 309593135@qq.com</a>
        <span>|</span>
        <span>Add： 13966 Century Avenue, Lixia District, Jinan City, Shandong Province</span>
    </div>
</body>
</html>

templates/bj_capacity.html
{% extends "base.html" %}

{% block main %}
     <button class="btn btn-primary" type="button">
          {% block capacity_title %}钣金工序{% endblock %} <span class="badge">35</span>
     </button>
    <div class="bj_capacity">
        <div class="bj_one">
            {% block photo1 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}

            {% block daka %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">
                鲁A18990
            </button>

            <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                        <form class="bj_daka">
                        <label><input type="submit" value="开始维修"></label>
                        </form>

                        <form class="bj_daka">
                            <label><input type="submit" value="结束维修"></label>
                        </form>
                    </div>
                </div>
            </div>
            {% endblock %}
            <br><br>

            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 40em;">
                40%
              </div>
            </div>
        </div>

        <div class="bj_one">
            {% block photo2 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}
            <span class="label label-warning">
                <a href="#">鲁A19555</a>
            </span>
            <br><br>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 70em;">
                70%
              </div>
            </div>
        </div>

        <div class="bj_one">
            {% block photo3 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}
            <span class="label label-warning">
                <a href="#">鲁A19555</a>
            </span><br><br>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 88em;">
                88%
              </div>
            </div>
        </div>

        <div class="bj_one">
            {% block photo4 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}
            <span class="label label-warning">
                <a href="#">鲁A19555</a>
            </span><br><br>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 75em;">
                75%
              </div>
            </div>
        </div>


        <div class="bj_one">
            {% block photo5 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}
            <span class="label label-warning">
                <a href="#">鲁A19555</a>
            </span><br><br>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 30em;">
                30%
              </div>
            </div>
        </div>

        <div class="bj_one">
            {% block photo6 %}<img class="bj_logo" src="../static/images/001.jpg">{% endblock %}
            <span class="label label-warning">
                <a href="#">鲁A19555</a>
            </span><br><br>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 50em;">
                50%
              </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/capacity.html
{% extends "base.html" %}

{% block nav_capacity_active %}active{% endblock %}


{% block main %}

    <div class="pt_capacity">
        {% block photo1 %}
            <button class="btn btn-primary" type="button">
                车间总产能 <span class="badge">15</span>
            </button>
        {% endblock %}
{#        <span class="label label-warning">#}
{#            <a href="#">鲁A19555</a>#}
{#        </span>#}
        <br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 40em;">
            产能负荷 40%
          </div>
        </div>
    </div>

    <div class="pt_capacity">
        {% block photo2 %}
            <button class="btn btn-primary" type="button">
                钣金工序 <span class="badge">20</span>
            </button>
        {% endblock %}
{#        <span class="label label-warning">#}
{#            <a href="#">鲁A19555</a>#}
{#        </span>#}
        <br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 60em;">
            产能负荷 60%
          </div>
        </div>
    </div>


    <div class="pt_capacity">
        {% block photo3 %}
            <button class="btn btn-primary" type="button">
                前处理工序 <span class="badge">20</span>
            </button>
        {% endblock %}
{#        <span class="label label-warning">#}
{#            <a href="#">鲁A19555</a>#}
{#        </span>#}
        <br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 30em;">
            产能负荷 30%
          </div>
        </div>
    </div>

    <div class="pt_capacity">
        {% block photo4 %}
            <button class="btn btn-primary" type="button">
                喷涂工序 <span class="badge">20</span>
            </button>
        {% endblock %}
{#        <span class="label label-warning">#}
{#            <a href="#">鲁A19555</a>#}
{#        </span>#}
        <br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 30em;">
            产能负荷 30%
          </div>
        </div>
    </div>

    <div class="pt_capacity">
        {% block photo5 %}
            <button class="btn btn-primary" type="button">
                抛光工序 <span class="badge">20</span>
            </button>
        {% endblock %}
{#        <span class="label label-warning">#}
{#            <a href="#">鲁A19555</a>#}
{#        </span>#}
        <br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 30em;">
            产能负荷 30%
          </div>
        </div>
    </div>

{% endblock %}

templates/car_message.html
{% extends "base.html" %}

{% block main %}
<button class="btn btn-primary car-message-title" type="button">
    鲁A18999
</button><br><br>

<div class="form-inline car-message-main">
    <div class="form-group">
        <label for="exampleInputName2">工单号.WIP</label>
        <label class="form-control" id="exampleInputName2">68999</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">车型.MODEL</label>
        <label class="form-control" id="exampleInputName2">5系</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">服务顾问.SA</label>
        <label class="form-control" id="exampleInputName2">张海龙</label>
    </div><br><br><br>

    <div class="form-group">
        <label for="exampleInputName2">预约进厂时间.TIME</label>
        <label class="form-control" id="exampleInputName2">2020年12月30日</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">工单登记时间.TIME</label>
        <label class="form-control" id="exampleInputName2">2020年12月30日</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">预约出厂时间.TIME</label>
        <label class="form-control" id="exampleInputName2">2020年12月30日</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">预估出厂时间.TIME</label>
        <label class="form-control" id="exampleInputName2">2020年12月30日</label>
    </div><br><br><br>

    <div class="form-group">
        <label for="exampleInputName2">钣金技师.MT</label>
        <label class="form-control" id="exampleInputName2">张敬旭</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">前处理技师.MT</label>
        <label class="form-control" id="exampleInputName2">张新</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">喷涂技师.MT</label>
        <label class="form-control" id="exampleInputName2">苏守杰</label>
    </div>

    <div class="form-group">
        <label for="exampleInputName2">维修件数.NUM</label>
        <label class="form-control" id="exampleInputName2">3件</label>
    </div>

    <br><br><br>

    <div class="form-group">
        <label for="exampleInputName2">维修项目.ITEM</label>
        <label class="form-control" id="exampleInputName2">前杠、机盖、左前侧围</label>
    </div>

    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <a class="btn btn-default">信息修改</a>
    </div>

</div>


{% endblock %}

templates/date_input.html
{% extends "base.html" %}

{% block nav_data_input_active %}active{% endblock %}


{% block main %}
    <form class="form-inline">
        <div class="form-group">
            <label for="exampleInputName2">车牌号码 .NUM</label>
            <input type="text" class="form-control" id="exampleInputName2" placeholder="CAR_NUM">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail2">工单号.WIP</label>
            <input type="text" class="form-control" id="exampleInputEmail2" placeholder="WIP">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail2">车型.MODEL</label>
            <select class="form-control" id="exampleInputEmail2">
                <option></option>
                <option>1系</option>
                <option>2系</option>
                <option>3系</option>
                <option>4系</option>
                <option>5系</option>
                <option>6系</option>
                <option>7系</option>
                <option>8系</option>
                <option>X1</option>
                <option>X2</option>
                <option>X3</option>
                <option>X4</option>
                <option>X5</option>
                <option>X6</option>
                <option>X7</option>
                <option>Z4</option>
                <option>MINI</option>
            </select>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail2">服务顾问.SA</label>
            <select class="form-control" id="exampleInputEmail2">
                <option></option>
                <option>张海龙</option>
                <option>孙永超</option>
                <option>徐淑员</option>
                <option>王加奎</option>
                <option>卢  杨</option>
                <option>继来光</option>
                <option>其他SA</option>
            </select>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail2">钣金技师.MT</label>
            <select class="form-control" id="exampleInputEmail2">
                <option></option>
                <option>张敬旭</option>
                <option>刘进秋</option>
                <option>吴庆宽</option>
                <option>姬传涛</option>
                <option>李 帅</option>
                <option>张万坤</option>
            </select>
        </div><br>

        <div class="form-group from-time">
            <label for="exampleInputEmail2">预约进厂时间.TIME</label>
            <input type="datetime-local" class="form-control" id="exampleInputEmail2">
        </div>

         <div class="form-group from-time">
            <label for="exampleInputEmail2">预约出厂时间.TIME</label>
            <input type="datetime-local" class="form-control" id="exampleInputEmail2">
         </div>

        <div class="form-group from-time">
            <label for="exampleInputEmail2">预估出厂时间.TIME</label>
            <input type="datetime-local" class="form-control" id="exampleInputEmail2">
        </div><br><br>

        <div class="checkbox-title">
            <label for="exampleInputEmail2">维修项目.ITEM:</label><br><br>
        </div>
        <div class="checkbox">
            <label class="checkbox-label">
              <input type="checkbox" value="" name="">前保险杠
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">前机盖
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左前侧围
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左前门
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左后门
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左后侧围
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左侧门槛
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左侧A柱
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左侧B柱
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">左侧上边梁
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">大灯
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">前风挡
            </label>

            <br><br>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">后保险杠
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">后机盖
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右前侧围
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右前门
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右后门
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右后侧围
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右侧门槛
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右侧A柱
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右侧B柱
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">右侧上边梁
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">尾灯
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">后风挡
            </label>

            <br><br>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">车顶维修
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">更换后侧围
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">更换后围板
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">更换前/后纵梁
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">更换左/右后视镜
            </label>

            <label class="checkbox-label">
              <input type="checkbox" value="" name="">全车喷漆
            </label>
        </div><br>
        <div class="data-input-button">
            <button type="reset" class="btn btn-default">重新录入</button>
            <button type="submit" class="btn btn-default">录入完成</button>
        </div>



    </form>
{% endblock %}

templates/date_report.html
{% extends "base.html" %}


{% block main %}
 <!-- 图表容器 DOM -->
 <div id="container" style="width: 80%;height:400px;margin: 80px auto;"></div>
 <!-- 引入 highcharts.js -->
 <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>

<!-- 需要保存导出功能模块文件是在 highcharts.js 之后引入 -->
<script src="http://cdn.hcharts.cn/highcharts/modules/exporting.js"></script>

<!-- 客户端导出功能模块为可选选项 -->
<script src="http://cdn.hcharts.cn/highcharts/modules/offline-exporting.js"></script>
 <script>
     // 图表配置
     var options = {
         chart: {
             type: 'bar'                          //指定图表的类型，默认是折线图（line）
         },
         title: {
             text: '钣喷车间数据报表'                 // 标题
         },
         xAxis: {
             categories: ['钣金', '前处理', '喷漆', '抛光', '质检']   // x 轴分类
         },
         yAxis: {
             title: {
                 text: '目前在修台次'                // y 轴标题
             }
         },
         series: [{                              // 数据列
             // name: '小明',                        // 数据列名
             // data: [1, 0, 4]                     // 数据
         }, {
             name: '台次',
             data: [20, 13, 10, 6, 15]
         }]
     };
     // 图表初始化函数
     var chart = Highcharts.chart('container', options);
 </script>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block nav_home_active %}active{% endblock %}

{% block main %}
    <!-- 首页内容显示区域开始 -->
    <table class="table table-hover">
        <tr class="info table-td">   
            <td>序号.<small>ID</small></td>
            <td class="hidden-xs">登记时间.<small>TIME</small></td>
            <td>车牌号码.<small>CAR_NUM</small></td>
            <td>工单号码.<small>WIP</small></td>
            <td>服务顾问.<small>SA</small></td>
            <td>钣金技师.<small>MT</small></td>
            <td class="hidden-xs">维修项目.<small>ITEM</small></td>
            <td>维修状态.<small>CON</small></td>
            <td class="hidden-xs">交付时间.<small>TIME</small></td>
            <td class="hidden-xs">是否快修.<small>TIME</small></td>
        </tr>
        <tr>
            <td><a  class="index_car_id" href="{% url 'mycar:car_message' %}">1</a></td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td>鲁A18650</td>
            <td>69885</td>
            <td>张海龙</td>
            <td>张敬旭</td>
            <td class="hidden-xs">前杠、机盖、侧围、大灯、车顶、后杠、左前车门、右前车门</td>
            <td>前处理</td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td class="hidden-xs">8小时</td>
        </tr>
        <tr>
            <td>2</td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td>鲁A18650</td>
            <td>69885</td>
            <td>张海龙</td>
            <td>张敬旭</td>
            <td class="hidden-xs">前杠、机盖、侧围、大灯、车顶、后杠、左前车门、右前车门</td>
            <td>前处理</td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td class="hidden-xs">24小时</td>
        </tr>
        <tr>
            <td>3</td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td>鲁A18650</td>
            <td>69885</td>
            <td>张海龙</td>
            <td>张敬旭</td>
            <td class="hidden-xs">前杠、机盖、侧围、大灯、车顶、后杠、左前车门、右前车门</td>
            <td>前处理</td>
            <td class="hidden-xs">2020年12月31日 18：30</td>
            <td class="hidden-xs">否</td>
        </tr>
    </table>
    <!-- 首页内容显示区域结束 -->
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
      {% load static %}
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="icon" href="{% static 'images/logo.ico' %}">
      <title>济南宝悦行汽车销售服务有限公司</title>>
      <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">

</head>


<body>
    <div class="container">
        <form class="form-signin">

            <h2 class="form-signin-heading">
                <img class="heading-logo" src="{% static 'images/logo.ico' %}">
                钣喷车间管理系统
            </h2>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
            <div class="div"></div>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>

            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> 记住我
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">登 陆</button>
      </form>
    </div>
</body>
</html>

templates/pt_pg_capacity.html
{% extends "base.html" %}

{% block main %}

    <div class="pt_capacity">
        {% block photo1 %}
            <button class="btn btn-primary" type="button">
                喷涂工序 <span class="badge">15</span>
            </button>
        {% endblock %}
        <span class="label label-warning">
            <a href="{% url 'mycar:pt_daka' %}">鲁A19555</a>
        </span><br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 40em;">
            40%
          </div>
        </div>
    </div>

    <div class="pt_capacity">
        {% block photo2 %}
            <button class="btn btn-primary" type="button">
                抛光工序 <span class="badge">20</span>
            </button>
        {% endblock %}
        <span class="label label-warning">
            <a href="{% url 'mycar:pg_daka' %}">鲁A19555</a>
        </span><br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 60em;">
            60%
          </div>
        </div>
    </div>


    <div class="pt_capacity">
        {% block photo3 %}
            <button class="btn btn-primary" type="button">
                终检工序 <span class="badge">20</span>
            </button>
        {% endblock %}
        <span class="label label-warning">
            <a href="#">鲁A19555</a>
        </span><br><br>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 30em;">
            30%
          </div>
        </div>
    </div>

{% endblock %}

templates/qcl_capacity.html
{% extends "bj_capacity.html" %}

{% block capacity_title %}前处理工序{% endblock %}

{% block photo1 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}
{% block daka %}
    <span class="label label-warning">
        <a href="{% url 'mycar:qcl_daka' %}">鲁A19555</a>
    </span>
{% endblock %}

{% block photo2 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}

{% block photo3 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}

{% block photo4 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}

{% block photo5 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}

{% block photo6 %}<img class="bj_logo" src="../static/images/channeng.png">{% endblock %}